# Site settings
title: Ryan Wilson-Perkin
email: ryanwilsonperkin@gmail.com
description: "The personal and professional site of Ryan Wilson-Perkin."
url: "https://ryanwilsonperkin.com"
image: /profile.jpg

# Build settings
markdown: kramdown
permalink: /posts/:year/:month/:day/:title
exclude: [README.md]
timezone: America/New_York

