# Site settings
title: Ryan Wilson-Perkin
email: ryanwilsonperkin@gmail.com
description: "The personal and professional site of Ryan Wilson-Perkin."
url: "http://ryanwilsonperkin.github.io"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md]
timezone: America/New_York
